{{- if and (and .Values.otelK8sClusterReceiver.enabled (eq (include "splunk-otel-collector.metricsEnabled" $) "true")) .Values.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}-otel-k8s-cluster-receiver
  labels:
    app: {{ template "splunk-otel-collector.name" . }}
    component: otel-k8s-cluster-receiver
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "splunk-otel-collector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Service }}
    app.kubernetes.io/component: otel-k8s-cluster-receiver
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "splunk-otel-collector.name" . }}
      component: otel-k8s-cluster-receiver
      release: {{ .Release.Name }}
{{ toYaml .Values.podDisruptionBudget | trim | indent 2 }}
{{- end }}
